---
- block:
  - name: Gatekeeper - 'enabled={{ apps_quarantine_enabled }}'
    command:
      argv:
        - spctl
        - "{{ item.line }}"
    loop:
      - { enable: 'yes', line: "--master-enable" }
      - { enable: 'no',  line: "--master-disable" }
    when: item.enable|bool == apps_quarantine_enabled|bool

  - name: Apps Quarantine - 'enabled={{ apps_quarantine_enabled }}'
    osx_defaults:
      domain: 'com.apple.LaunchServices'
      key: 'LSQuarantine'
      type: bool
      value: "{{ apps_quarantine_enabled }}"

  - name: Apps Quarantine - restart LaunchServices
    command: killall launchservicesd
    ignore_errors: yes
  # end block
  when: apps_quarantine_enabled is defined
  become: yes
